---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: holoinsight-agent-example-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: holoinsight-example
roleRef:
  kind: ClusterRole
  name: holoinsight-agent-example-clusterrole
  apiGroup: rbac.authorization.k8s.io
